// Country name + ISO2 + international dial code, used to build the
// country picker on the VCF panel submission page.
const COUNTRIES = [
  { n: 'Tanzania', c: 'TZ', d: '255' },
  { n: 'Kenya', c: 'KE', d: '254' },
  { n: 'Uganda', c: 'UG', d: '256' },
  { n: 'Rwanda', c: 'RW', d: '250' },
  { n: 'Burundi', c: 'BI', d: '257' },
  { n: 'DR Congo', c: 'CD', d: '243' },
  { n: 'Zambia', c: 'ZM', d: '260' },
  { n: 'Malawi', c: 'MW', d: '265' },
  { n: 'Mozambique', c: 'MZ', d: '258' },
  { n: 'South Africa', c: 'ZA', d: '27' },
  { n: 'Zimbabwe', c: 'ZW', d: '263' },
  { n: 'Botswana', c: 'BW', d: '267' },
  { n: 'Namibia', c: 'NA', d: '264' },
  { n: 'Ethiopia', c: 'ET', d: '251' },
  { n: 'Somalia', c: 'SO', d: '252' },
  { n: 'South Sudan', c: 'SS', d: '211' },
  { n: 'Sudan', c: 'SD', d: '249' },
  { n: 'Eritrea', c: 'ER', d: '291' },
  { n: 'Djibouti', c: 'DJ', d: '253' },
  { n: 'Nigeria', c: 'NG', d: '234' },
  { n: 'Ghana', c: 'GH', d: '233' },
  { n: 'Ivory Coast', c: 'CI', d: '225' },
  { n: 'Senegal', c: 'SN', d: '221' },
  { n: 'Mali', c: 'ML', d: '223' },
  { n: 'Niger', c: 'NE', d: '227' },
  { n: 'Guinea', c: 'GN', d: '224' },
  { n: 'Benin', c: 'BJ', d: '229' },
  { n: 'Togo', c: 'TG', d: '228' },
  { n: 'Sierra Leone', c: 'SL', d: '232' },
  { n: 'Liberia', c: 'LR', d: '231' },
  { n: 'Cameroon', c: 'CM', d: '237' },
  { n: 'Chad', c: 'TD', d: '235' },
  { n: 'Central African Republic', c: 'CF', d: '236' },
  { n: 'Gabon', c: 'GA', d: '241' },
  { n: 'Congo', c: 'CG', d: '242' },
  { n: 'Angola', c: 'AO', d: '244' },
  { n: 'Egypt', c: 'EG', d: '20' },
  { n: 'Libya', c: 'LY', d: '218' },
  { n: 'Tunisia', c: 'TN', d: '216' },
  { n: 'Algeria', c: 'DZ', d: '213' },
  { n: 'Morocco', c: 'MA', d: '212' },
  { n: 'Gambia', c: 'GM', d: '220' },
  { n: 'Guinea-Bissau', c: 'GW', d: '245' },
  { n: 'Mauritania', c: 'MR', d: '222' },
  { n: 'Comoros', c: 'KM', d: '269' },
  { n: 'Madagascar', c: 'MG', d: '261' },
  { n: 'Mauritius', c: 'MU', d: '230' },
  { n: 'Seychelles', c: 'SC', d: '248' },
  { n: 'Lesotho', c: 'LS', d: '266' },
  { n: 'Eswatini', c: 'SZ', d: '268' },
  { n: 'Equatorial Guinea', c: 'GQ', d: '240' },
  { n: 'Cape Verde', c: 'CV', d: '238' },
  { n: 'Sao Tome and Principe', c: 'ST', d: '239' },
  { n: 'India', c: 'IN', d: '91' },
  { n: 'Pakistan', c: 'PK', d: '92' },
  { n: 'Bangladesh', c: 'BD', d: '880' },
  { n: 'Sri Lanka', c: 'LK', d: '94' },
  { n: 'Nepal', c: 'NP', d: '977' },
  { n: 'China', c: 'CN', d: '86' },
  { n: 'Japan', c: 'JP', d: '81' },
  { n: 'South Korea', c: 'KR', d: '82' },
  { n: 'Indonesia', c: 'ID', d: '62' },
  { n: 'Malaysia', c: 'MY', d: '60' },
  { n: 'Singapore', c: 'SG', d: '65' },
  { n: 'Philippines', c: 'PH', d: '63' },
  { n: 'Thailand', c: 'TH', d: '66' },
  { n: 'Vietnam', c: 'VN', d: '84' },
  { n: 'Myanmar', c: 'MM', d: '95' },
  { n: 'Cambodia', c: 'KH', d: '855' },
  { n: 'Saudi Arabia', c: 'SA', d: '966' },
  { n: 'United Arab Emirates', c: 'AE', d: '971' },
  { n: 'Qatar', c: 'QA', d: '974' },
  { n: 'Kuwait', c: 'KW', d: '965' },
  { n: 'Bahrain', c: 'BH', d: '973' },
  { n: 'Oman', c: 'OM', d: '968' },
  { n: 'Yemen', c: 'YE', d: '967' },
  { n: 'Jordan', c: 'JO', d: '962' },
  { n: 'Lebanon', c: 'LB', d: '961' },
  { n: 'Iraq', c: 'IQ', d: '964' },
  { n: 'Iran', c: 'IR', d: '98' },
  { n: 'Israel', c: 'IL', d: '972' },
  { n: 'Palestine', c: 'PS', d: '970' },
  { n: 'Turkey', c: 'TR', d: '90' },
  { n: 'Afghanistan', c: 'AF', d: '93' },
  { n: 'United Kingdom', c: 'GB', d: '44' },
  { n: 'Ireland', c: 'IE', d: '353' },
  { n: 'France', c: 'FR', d: '33' },
  { n: 'Germany', c: 'DE', d: '49' },
  { n: 'Spain', c: 'ES', d: '34' },
  { n: 'Portugal', c: 'PT', d: '351' },
  { n: 'Italy', c: 'IT', d: '39' },
  { n: 'Netherlands', c: 'NL', d: '31' },
  { n: 'Belgium', c: 'BE', d: '32' },
  { n: 'Switzerland', c: 'CH', d: '41' },
  { n: 'Austria', c: 'AT', d: '43' },
  { n: 'Sweden', c: 'SE', d: '46' },
  { n: 'Norway', c: 'NO', d: '47' },
  { n: 'Denmark', c: 'DK', d: '45' },
  { n: 'Finland', c: 'FI', d: '358' },
  { n: 'Poland', c: 'PL', d: '48' },
  { n: 'Greece', c: 'GR', d: '30' },
  { n: 'Russia', c: 'RU', d: '7' },
  { n: 'Ukraine', c: 'UA', d: '380' },
  { n: 'Romania', c: 'RO', d: '40' },
  { n: 'Czech Republic', c: 'CZ', d: '420' },
  { n: 'Hungary', c: 'HU', d: '36' },
  { n: 'United States', c: 'US', d: '1' },
  { n: 'Canada', c: 'CA', d: '1' },
  { n: 'Mexico', c: 'MX', d: '52' },
  { n: 'Brazil', c: 'BR', d: '55' },
  { n: 'Argentina', c: 'AR', d: '54' },
  { n: 'Chile', c: 'CL', d: '56' },
  { n: 'Colombia', c: 'CO', d: '57' },
  { n: 'Peru', c: 'PE', d: '51' },
  { n: 'Venezuela', c: 'VE', d: '58' },
  { n: 'Australia', c: 'AU', d: '61' },
  { n: 'New Zealand', c: 'NZ', d: '64' },
];
